spring:
  application:
    name: dubbo-controller
  session:
    #spring session采用的数据源类型
    store-type: redis
    redis:
      #配置session在redis里的命名空间
      namespace: security_session
      #配置session的保存触发方式
      flush-mode: on_save
  redis:
    timeout: 5000
    jedis:
      pool:
        max-active: 500
        min-idle: 10
        max-idle: 50
server:
  port: 8080
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
dubbo:
  application:
    name: dubbo-controller
  consumer:
    timeout: 10000
    retries: 0
  protocol:
    name: dubbo
    port: 20882
common:
  jedis: true
  redis: true
  jackson: true
