server:
  port: 8080
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: dubbo-controller
dubbo:
  registry:
    address: nacos://172.17.0.1:8848
    filter: tracing
  application:
    name: dubbo-controller
  consumer:
    timeout: 10000
    retries: 0
  protocol:
    name: dubbo
    port: 20882
zipkin:
  address: http://172.17.0.1:9411/api/v2/spans
  service-name: controller
  sampling-rate: 1
jedis:
  password: 123456
common:
  request-log: true
  ajax-jackson: true
  jedis: true