spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
zipkin:
  address: http://47.101.151.125:9411/api/v2/spans
  service-name: controller
  sampling-rate: 1
jedis:
  password: 123456
common:
  jedis: true
  redis: true
